export enum Permission {
  PLAYERS_READ = 'players:read',
  PLAYERS_WRITE = 'players:write',
  TEAMS_READ = 'teams:read',
  TEAMS_WRITE = 'teams:write',
  FIELDS_READ = 'fields:read',
  FIELDS_WRITE = 'fields:write',
  OPEN_GAMES_READ = 'open-games:read',
  OPEN_GAMES_WRITE = 'open-games:write',
  REVIEWS_READ = 'reviews:read',
  REVIEWS_WRITE = 'reviews:write',
  SEASONS_READ = 'seasons:read',
  SEASONS_WRITE = 'seasons:write',
  MATCHES_READ = 'matches:read',
  MATCHES_WRITE = 'matches:write',
  RANKINGS_READ = 'rankings:read',
  NOTIFICATIONS_WRITE = 'notifications:write',
}
